
public class ExceptionTest {
	
	public static void main(String[] args) {
		try{
			int d =0;
			int n =10;
			
			int fraction = n/d;
			System.out.println("HI");
			}
		
		
		finally{
			Exception e=new Exception();
				System.out.println("In the other TryCatch clock due to again Exception = "+e.getMessage());
				}
			
		}
	}


